import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Aside } from "@/components/Aside";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <span className="main-section-bg-1"></span>
                <span className="main-section-bg-2"></span>
                <span className="main-section-bg-3"></span>
                <Aside />
                <main>{children}</main>
            </body>
        </html>
    );
};

export default RootLayout;
